Ext.define('Lybrary.model.Book',{
    extend: 'Ext.data.Model',
    fields:[{
        type:'int',
        name:'id'
    },{
        type:'string',
        name:'name'
    },{
        type:'string',
        name:'editorid'
    },{
        type:'string',
        name:'categoryid'
    },{
        type:'string',
        name:'statusid'
    },
    //fields form join
    {
        type:'string',
        name:'editorname'
    },{
        type:'string',
        name:'categoryname'
    },{
        type:'string',
        name:'statusname'
    }]
});